import { mkdirSync, writeFileSync } from "node:fs";
import { levelsForMode } from "../src/data/campaign";
import {
  createGolfSimulationState,
  simulateShotToRest,
  type GolfSimulationState,
  type SimulationShot
} from "../src/systems/GolfSimulation";
import type { LevelDefinition, Vec2 } from "../src/types";

type AgentKind="learned"|"naive"|"explorer";
type Audit2Status="PASS"|"REVIEW"|"BLOCKER";
interface SolvedRun{strokes:number;time:number;shots:SimulationShot[];state:GolfSimulationState;}
interface SearchNode extends SolvedRun{score:number;}
interface HumanProfile{name:string;angleSigma:number;powerSigma:number;trials:number;}
interface ProfileResult{name:string;successRate:number;voidRate:number;medianEndDistance:number;}
interface NaiveTrapResult{triggerRate:number;punishRate:number;sampleCount:number;}
interface RecoveryResult{sampleCount:number;recoverableRate:number;movingTimeoutRate:number;}
interface NominalStep{before:GolfSimulationState;shot:SimulationShot;after:GolfSimulationState;sunk:boolean;}
interface Audit2Row{
  id:string;mode:string;target:number;learnedStrokes:number|null;naiveStrokes:number|null;explorerStrokes:number|null;routeFamilies:number;
  profiles:ProfileResult[];minShotTolerance:number|null;naiveTrap:NaiveTrapResult|null;mechanicRelevant:boolean|null;recovery:RecoveryResult;
  minRestEdgeDistance:number|null;flags:string[];status:Audit2Status;
}

const FULL=process.env.AUDIT2_MODE==="full";
const STRICT=process.env.AUDIT2_STRICT==="1";
const FIELD={x:28,y:28,w:484,h:904},TAU=Math.PI*2;
const rad=(d:number)=>d*Math.PI/180,deg=(r:number)=>r*180/Math.PI;
const wrap=(a:number)=>((a%TAU)+TAU)%TAU,clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const dist=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y);
function hashString(value:string):number{let h=2166136261>>>0;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function rng(seed:number):()=>number{let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function gaussian(random:()=>number):number{const u=Math.max(1e-9,random()),v=Math.max(1e-9,random());return Math.sqrt(-2*Math.log(u))*Math.cos(TAU*v);}
function routePoints(level:LevelDefinition):Vec2[]{return level.designPath?.length?[level.ball,...level.designPath.filter(p=>dist(p,level.ball)>4),level.hole]:[level.ball,level.hole];}
function nextRoutePoint(level:LevelDefinition,state:GolfSimulationState):Vec2{const pts=routePoints(level);let nearest=0,best=Infinity;for(let i=0;i<pts.length;i++){const d=dist(state.ball,pts[i]!);if(d<best){best=d;nearest=i;}}return pts[Math.min(pts.length-1,nearest+1)]??level.hole;}
function stateKey(state:GolfSimulationState):string{return[Math.round(state.ball.x/18),Math.round(state.ball.y/18),state.popWalls.map(x=>x.active?1:0).join(""),state.popBumpers.map(x=>x.active?1:0).join(""),state.popVoids.map(x=>x.active?1:0).join("")].join(":");}
function score(level:LevelDefinition,state:GolfSimulationState,agent:AgentKind):number{const hole=dist(state.ball,level.hole);if(agent==="naive")return hole+state.time*.65;if(agent==="explorer")return hole+state.time*.45+(state.triggeredTraps.length?8:0);const next=dist(state.ball,nextRoutePoint(level,state));return hole+next*.25+state.time*.6+(level.mode==="troll"&&state.triggeredTraps.length>0?-10:0)+(level.primaryMechanic&&state.touchedMechanics.includes(level.primaryMechanic)?-14:0);}
function uniqueShots(shots:SimulationShot[]):SimulationShot[]{const map=new Map<string,SimulationShot>();for(const shot of shots){const key=`${Math.round(deg(shot.angle)*2)}:${Math.round(shot.power*100)}`;if(!map.has(key))map.set(key,shot);}return[...map.values()];}
function candidateShots(level:LevelDefinition,state:GolfSimulationState,agent:AgentKind):SimulationShot[]{
  const b=state.ball,out:SimulationShot[]=[];
  if(agent==="explorer"){const step=FULL?12:20,powers=FULL?[.30,.42,.54,.66,.78,.90,1]:[.38,.56,.74,.92,1];for(let d=0;d<360;d+=step)for(const power of powers)out.push({angle:rad(d),power});return out;}
  if(agent==="naive"){const anchors=[level.hole,routePoints(level)[1]??level.hole],offsets=FULL?[-28,-18,-10,-5,0,5,10,18,28]:[-24,-12,0,12,24],powers=FULL?[.42,.56,.70,.84,.96,1]:[.50,.68,.86,1];for(const target of anchors){const base=Math.atan2(target.y-b.y,target.x-b.x);for(const d of offsets)for(const power of powers)out.push({angle:wrap(base+rad(d)),power});}for(let d=0;d<360;d+=(FULL?30:45))for(const power of[.62,.90])out.push({angle:rad(d),power});return uniqueShots(out);}
  const anchors=[level.hole,nextRoutePoint(level,state),...routePoints(level)].filter((p,i,a)=>a.findIndex(q=>dist(p,q)<8)===i),offsets=FULL?[-34,-24,-16,-10,-6,-3,0,3,6,10,16,24,34]:[-28,-14,-6,0,6,14,28],powers=FULL?[.28,.38,.48,.58,.68,.78,.88,.96,1]:[.34,.50,.66,.82,.96];
  for(const target of anchors){const base=Math.atan2(target.y-b.y,target.x-b.x);for(const d of offsets)for(const power of powers)out.push({angle:wrap(base+rad(d)),power});}for(let d=0;d<360;d+=(FULL?24:36))for(const power of[.48,.72,.94])out.push({angle:rad(d),power});return uniqueShots(out);
}
function solveFromState(level:LevelDefinition,start:GolfSimulationState,agent:AgentKind,maxDepth:number,widthOverride?:number):SolvedRun[]{
  let beam:SearchNode[]=[{state:start,strokes:0,time:start.time,shots:[],score:0}];const width=widthOverride??(agent==="learned"?(FULL?150:64):agent==="naive"?(FULL?70:30):(FULL?90:42)),maxSolutions=FULL?24:12;
  for(let depth=1;depth<=maxDepth;depth++){const dedupe=new Map<string,SearchNode>(),solved:SolvedRun[]=[];for(const node of beam){for(const shot of candidateShots(level,node.state,agent)){const result=simulateShotToRest(level,node.state,shot,FULL?10:8);if(result.voided||result.state.moving)continue;const run:SearchNode={state:result.state,strokes:depth,time:result.state.time,shots:[...node.shots,shot],score:0};if(result.sunk){solved.push(run);if(solved.length>=maxSolutions)break;continue;}run.score=score(level,result.state,agent);const key=stateKey(result.state),old=dedupe.get(key);if(!old||run.score<old.score)dedupe.set(key,run);}if(solved.length>=maxSolutions)break;}if(solved.length)return solved.sort((a,b)=>a.time-b.time);beam=[...dedupe.values()].sort((a,b)=>a.score-b.score).slice(0,width);if(!beam.length)break;}return[];
}
function solve(level:LevelDefinition,agent:AgentKind,maxDepth:number):SolvedRun[]{return solveFromState(level,createGolfSimulationState(level),agent,maxDepth);}
function replay(level:LevelDefinition,shots:SimulationShot[]):{state:GolfSimulationState;sunk:boolean;voided:boolean;rests:Vec2[]}{let state=createGolfSimulationState(level),voided=false,sunk=false;const rests:Vec2[]=[];for(const shot of shots){const result=simulateShotToRest(level,state,shot,FULL?10:8);state=result.state;rests.push({x:state.ball.x,y:state.ball.y});if(result.voided){voided=true;break;}if(result.sunk){sunk=true;break;}}return{state,sunk,voided,rests};}
function nominalSteps(level:LevelDefinition,best:SolvedRun|null):NominalStep[]{if(!best)return[];let state=createGolfSimulationState(level);const out:NominalStep[]=[];for(const shot of best.shots){const before=state,result=simulateShotToRest(level,state,shot,FULL?10:8);state=result.state;out.push({before,shot,after:state,sunk:result.sunk});if(result.sunk||result.voided)break;}return out;}
function acceptablePerturbation(level:LevelDefinition,step:NominalStep,result:ReturnType<typeof simulateShotToRest>):boolean{
  if(result.voided||result.state.moving)return false;if(result.sunk)return true;
  const beforeHole=dist(step.before.ball,level.hole),afterHole=dist(result.state.ball,level.hole),nominalHole=dist(step.after.ball,level.hole),restDelta=dist(result.state.ball,step.after.ball),target=nextRoutePoint(level,step.before),beforeTarget=dist(step.before.ball,target),afterTarget=dist(result.state.ball,target);
  if(step.sunk)return afterHole<=72;if(restDelta<=96)return true;if(afterHole<=nominalHole+85&&afterHole<beforeHole-35)return true;if(afterTarget<beforeTarget-35&&afterHole<beforeHole+55)return true;return false;
}
function profileRun(level:LevelDefinition,best:SolvedRun|null,profile:HumanProfile):ProfileResult{
  const steps=nominalSteps(level,best);if(!steps.length)return{name:profile.name,successRate:0,voidRate:0,medianEndDistance:9999};
  const random=rng(hashString(`${level.id}:${profile.name}:${FULL?"full":"fast"}`));let accepted=0,voids=0,total=0;const distances:number[]=[];const perShot=Math.max(8,Math.ceil(profile.trials/steps.length));
  for(const step of steps)for(let i=0;i<perShot;i++){const shot={angle:wrap(step.shot.angle+rad(gaussian(random)*profile.angleSigma)),power:clamp(step.shot.power+gaussian(random)*profile.powerSigma,.18,1)},result=simulateShotToRest(level,step.before,shot,FULL?10:8);total++;if(result.voided)voids++;if(acceptablePerturbation(level,step,result))accepted++;distances.push(dist(result.state.ball,level.hole));}
  distances.sort((a,b)=>a-b);return{name:profile.name,successRate:total?accepted/total:0,voidRate:total?voids/total:0,medianEndDistance:distances[Math.floor(distances.length/2)]??9999};
}
function shotTolerance(level:LevelDefinition,best:SolvedRun|null):number|null{const steps=nominalSteps(level,best);if(!steps.length)return null;let minimum=1;const angleD=FULL?[-8,-6,-4,-2,0,2,4,6,8]:[-7,-4,0,4,7],powerD=FULL?[-.10,-.075,-.05,-.025,0,.025,.05,.075,.10]:[-.08,-.04,0,.04,.08];for(const step of steps){let ok=0,total=0;for(const da of angleD)for(const dp of powerD){const shot={angle:wrap(step.shot.angle+rad(da)),power:clamp(step.shot.power+dp,.18,1)},result=simulateShotToRest(level,step.before,shot,FULL?10:8);total++;if(acceptablePerturbation(level,step,result))ok++;}minimum=Math.min(minimum,total?ok/total:0);}return minimum;}
function firstRest(level:LevelDefinition,run:SolvedRun):Vec2{const result=simulateShotToRest(level,createGolfSimulationState(level),run.shots[0]!,FULL?10:8);return{x:result.state.ball.x,y:result.state.ball.y};}
function routeFamilyCount(level:LevelDefinition,runs:SolvedRun[]):number{const families=new Set<string>();for(const run of runs){if(!run.shots.length)continue;const shot=run.shots[0]!,rest=firstRest(level,run);families.add(`${Math.round(deg(shot.angle)/25)}:${Math.round(rest.x/90)}:${Math.round(rest.y/90)}`);}return families.size;}
function withoutPopTraps(level:LevelDefinition):LevelDefinition{return{...level,popWalls:[],popBumpers:[],popVoids:[]};}
function naiveTrapProbe(level:LevelDefinition):NaiveTrapResult|null{if(level.mode!=="troll")return null;const targets=[level.hole,routePoints(level)[1]??level.hole],offsets=FULL?[-18,-12,-6,0,6,12,18]:[-15,-7,0,7,15],powers=FULL?[.55,.68,.81,.94,1]:[.62,.78,.94];let samples=0,triggers=0,punishes=0;const noTraps=withoutPopTraps(level);for(const target of targets){const base=Math.atan2(target.y-level.ball.y,target.x-level.ball.x);for(const da of offsets)for(const power of powers){samples++;const shot={angle:wrap(base+rad(da)),power},actual=simulateShotToRest(level,createGolfSimulationState(level),shot,7),control=simulateShotToRest(noTraps,createGolfSimulationState(noTraps),shot,7),triggered=actual.state.triggeredTraps.length>0;if(triggered)triggers++;const positionDelta=dist(actual.state.ball,control.state.ball),distancePenalty=dist(actual.state.ball,level.hole)-dist(control.state.ball,level.hole);if(actual.voided||(triggered&&(control.sunk&&!actual.sunk||positionDelta>55||distancePenalty>70)))punishes++;}}return{triggerRate:samples?triggers/samples:0,punishRate:samples?punishes/samples:0,sampleCount:samples};}
function mechanicRelevant(level:LevelDefinition,best:SolvedRun|null,trap:NaiveTrapResult|null):boolean|null{if(!level.primaryMechanic||!best)return null;if(level.mode==="troll"&&trap)return trap.punishRate>.08;if(level.primaryMechanic==="wall")return null;return best.state.touchedMechanics.includes(level.primaryMechanic)||best.state.triggeredTraps.some(t=>t.startsWith(`${level.primaryMechanic}:`));}
function hasProgressShot(level:LevelDefinition,state:GolfSimulationState):boolean{const startHole=dist(state.ball,level.hole),target=nextRoutePoint(level,state),startTarget=dist(state.ball,target);for(let d=0;d<360;d+=30)for(const power of[.42,.66,.90]){const result=simulateShotToRest(level,state,{angle:rad(d),power},7);if(result.sunk)return true;if(result.voided||result.state.moving)continue;const holeGain=startHole-dist(result.state.ball,level.hole),targetGain=startTarget-dist(result.state.ball,target);if(holeGain>70||targetGain>75)return true;}return false;}
function recoveryProbe(level:LevelDefinition):RecoveryResult{const random=rng(hashString(`${level.id}:recovery`)),count=FULL?36:18;let tested=0,recoveries=0,moving=0;for(let i=0;i<count;i++){const shot={angle:random()*TAU,power:.28+random()*.72},first=simulateShotToRest(level,createGolfSimulationState(level),shot,7);if(first.sunk||first.voided)continue;tested++;if(first.state.moving){moving++;continue;}if(hasProgressShot(level,first.state))recoveries++;}return{sampleCount:tested,recoverableRate:tested?recoveries/tested:1,movingTimeoutRate:tested?moving/tested:0};}
function edgeDistance(p:Vec2):number{return Math.min(p.x-FIELD.x,FIELD.x+FIELD.w-p.x,p.y-FIELD.y,FIELD.y+FIELD.h-p.y);}
function minRestEdge(level:LevelDefinition,best:SolvedRun|null):number|null{if(!best)return null;const replayed=replay(level,best.shots);return Math.min(edgeDistance(level.ball),...replayed.rests.map(edgeDistance));}
function statusFor(flags:string[]):Audit2Status{return flags.some(x=>x.startsWith("BLOCKER:"))?"BLOCKER":flags.length?"REVIEW":"PASS";}
function auditLevel(level:LevelDefinition):Audit2Row{
  const maxDepth=Math.max(5,(level.twoStar.maxStrokes??4)+1),learnedRuns=solve(level,"learned",maxDepth),naiveRuns=solve(level,"naive",Math.min(maxDepth,4)),explorerRuns=solve(level,"explorer",Math.min(maxDepth,4)),learned=learnedRuns[0]??null,naive=naiveRuns[0]??null,explorer=explorerRuns[0]??null;
  const profiles:HumanProfile[]=[{name:"mouse",angleSigma:1.5,powerSigma:.015,trials:FULL?220:72},{name:"touch",angleSigma:3.25,powerSigma:.035,trials:FULL?280:96},{name:"casual",angleSigma:5.5,powerSigma:.060,trials:FULL?320:120}],profileResults=profiles.map(p=>profileRun(level,learned,p)),tolerance=shotTolerance(level,learned),trap=naiveTrapProbe(level),recovery=recoveryProbe(level),families=routeFamilyCount(level,[...learnedRuns,...explorerRuns]),relevant=mechanicRelevant(level,learned,trap),edge=minRestEdge(level,learned),flags:string[]=[];
  const touch=profileResults.find(x=>x.name==="touch")!,casual=profileResults.find(x=>x.name==="casual")!;
  if(!learned)flags.push("BLOCKER:NO_LEARNED_ROUTE");if(learned&&touch.successRate<.30)flags.push(`BLOCKER:HUMAN_EXECUTION:${Math.round(touch.successRate*100)}%`);else if(learned&&touch.successRate<.62)flags.push(`TOUCH_PRECISION_RISK:${Math.round(touch.successRate*100)}%`);if(learned&&casual.successRate<.38)flags.push(`CASUAL_EXECUTION_RISK:${Math.round(casual.successRate*100)}%`);if(tolerance!==null&&tolerance<.20)flags.push(`BLOCKER:PIXEL_PERFECT:${Math.round(tolerance*100)}%`);else if(tolerance!==null&&tolerance<.48)flags.push(`NARROW_SHOT_WINDOW:${Math.round(tolerance*100)}%`);
  if(level.mode==="troll"&&trap&&trap.punishRate<.08)flags.push(`BLOCKER:TRAP_IRRELEVANT:${Math.round(trap.punishRate*100)}%`);else if(level.mode==="troll"&&trap&&trap.punishRate<.22)flags.push(`WEAK_TROLL_CONSEQUENCE:${Math.round(trap.punishRate*100)}%`);if(relevant===false)flags.push("MECHANIC_RELEVANCE_LOW");if(recovery.recoverableRate<.58)flags.push(`RECOVERY_RISK:${Math.round(recovery.recoverableRate*100)}%`);if(recovery.movingTimeoutRate>.04)flags.push(`MOVING_TIMEOUT_RISK:${Math.round(recovery.movingTimeoutRate*100)}%`);if(families<=1&&level.group>=3)flags.push("LOW_ROUTE_DIVERSITY:1");if(edge!==null&&edge<18)flags.push(`EDGE_REST_RISK:${Math.round(edge)}px`);const target=level.threeStar.maxStrokes??0,bestAny=Math.min(learned?.strokes??99,naive?.strokes??99,explorer?.strokes??99);if(target>=3&&bestAny===1)flags.push("CHEESE_HIO");
  return{id:level.id,mode:level.mode,target,learnedStrokes:learned?.strokes??null,naiveStrokes:naive?.strokes??null,explorerStrokes:explorer?.strokes??null,routeFamilies:families,profiles:profileResults,minShotTolerance:tolerance,naiveTrap:trap,mechanicRelevant:relevant,recovery,minRestEdgeDistance:edge,flags,status:statusFor(flags)};
}
function pct(v:number|null|undefined):string{return v===null||v===undefined?"n/a":`${Math.round(v*100)}%`;}
function legacyH3Fixture():LevelDefinition{const current=levelsForMode("troll").find(x=>x.id==="troll-03")!;return{...current,id:"fixture-hard-03-rc5",walls:[{x:330,y:520,w:182,h:24},{x:28,y:330,w:300,h:24}],popVoids:[{x:28,y:590,w:372,h:126,triggerX:270,triggerY:750,triggerRadius:105}],designPath:[{x:452,y:730},{x:452,y:568},{x:220,y:500},{x:220,y:390},{x:390,y:278},{x:420,y:142}]};}

const rows:Audit2Row[]=[];console.log(`\nAUDIT 2.0 · ${FULL?"full human-model":"fast calibration"}${STRICT?" · strict":""}`);
for(const mode of["classic","troll"]as const){console.log(`\n=== ${mode.toUpperCase()} ===`);for(const level of levelsForMode(mode)){const row=auditLevel(level);rows.push(row);const touch=row.profiles.find(x=>x.name==="touch")!,casual=row.profiles.find(x=>x.name==="casual")!;console.log(`${row.id.padEnd(10)} learned=${String(row.learnedStrokes??"?").padEnd(2)} naive=${String(row.naiveStrokes??"?").padEnd(2)} families=${String(row.routeFamilies).padEnd(2)} touch=${pct(touch.successRate).padEnd(4)} casual=${pct(casual.successRate).padEnd(4)} shotTol=${pct(row.minShotTolerance).padEnd(4)} recover=${pct(row.recovery.recoverableRate).padEnd(4)} trap=${row.naiveTrap?pct(row.naiveTrap.punishRate):"n/a"} ${row.status}${row.flags.length?` [${row.flags.join(" | ")}]`:""}`);}}
const currentH3=rows.find(x=>x.id==="troll-03")!,legacy=auditLevel(legacyH3Fixture()),legacyTouch=legacy.profiles.find(x=>x.name==="touch")!.successRate,currentTouch=currentH3.profiles.find(x=>x.name==="touch")!.successRate,regressionPass=(legacy.minShotTolerance??1)<(currentH3.minShotTolerance??0)&&legacyTouch<currentTouch;
console.log(`\nREGRESSION H03 RC5→RC5.1: old touch=${pct(legacyTouch)} tol=${pct(legacy.minShotTolerance)} · current touch=${pct(currentTouch)} tol=${pct(currentH3.minShotTolerance)} · ${regressionPass?"PASS":"REVIEW"}`);
const summary={pass:rows.filter(r=>r.status==="PASS").length,review:rows.filter(r=>r.status==="REVIEW").length,blocker:rows.filter(r=>r.status==="BLOCKER").length,total:rows.length};console.log(`\nAUDIT 2.0 SUMMARY: ${summary.pass}/${summary.total} pass · ${summary.review} review · ${summary.blocker} blocker`);
mkdirSync("artifacts",{recursive:true});writeFileSync("artifacts/audit2-report.json",JSON.stringify({generatedAt:new Date().toISOString(),mode:FULL?"full":"fast",summary,regression:{id:"hard-03-rc5-human-playability",pass:regressionPass,legacy,current:currentH3},rows},null,2));
const md=["# Troll Golf · Audit 2.0",`Mode: **${FULL?"full human-model":"fast calibration"}**`,`Summary: **${summary.pass}/${summary.total} PASS · ${summary.review} REVIEW · ${summary.blocker} BLOCKER**`,`H03 regression: **${regressionPass?"PASS":"REVIEW"}**`,"","| Hole | Learned | Naive | Families | Touch | Casual | Shot tolerance | Recovery | Trap consequence | Status |","|---|---:|---:|---:|---:|---:|---:|---:|---:|---|",...rows.map(r=>{const touch=r.profiles.find(x=>x.name==="touch")!,casual=r.profiles.find(x=>x.name==="casual")!;return`| ${r.id} | ${r.learnedStrokes??"?"} | ${r.naiveStrokes??"?"} | ${r.routeFamilies} | ${pct(touch.successRate)} | ${pct(casual.successRate)} | ${pct(r.minShotTolerance)} | ${pct(r.recovery.recoverableRate)} | ${r.naiveTrap?pct(r.naiveTrap.punishRate):"n/a"} | ${r.status}${r.flags.length?` · ${r.flags.join(", ")}`:""} |`;})];writeFileSync("artifacts/audit2-report.md",md.join("\n"));console.log("Reports: artifacts/audit2-report.json + artifacts/audit2-report.md");if(STRICT&&(summary.blocker>0||!regressionPass))process.exitCode=1;
